### PR TITLE
Issue-333: Android Gradle plugin 7.0.0 support

### PR DESCRIPTION
**Pull request by DDeg**
Added support for AGP 7.0, fix for https://github.com/kezong/fat-aar-android/issues/333. 

Tested changes with AGP 3.0+ and Gradle 7.0+. Probably, needs more testing with different old versions AGP and Gradle.
Currently, AGP 7.0 limited with usage of Java 11 and Gradle 7.0 respectively.

### CODE REVIEW

**Comment by DDeg** [comment]
@kezong please, review at your convenience.

**Comment by kezong** [comment]
Nice job, I will check it later.

**Comment by ChenJiaJian96** [comment]
Our team is using this plugin for gradle 7.0 and met the same problem.
Hope you can check and publish it soon.

Thanks sincerely.

**Comment by aasitnikov** [comment]
As I can see, the only major change in this PR is replacing `mVariant.getApplicationId()` with `mVariant.applicationIdTextResource.asString()`. But AGP 7.0.1 fixes the issue with `getApplicationId()`, so perhaps this change is no longer necessary

**Comment by DDeg** [comment]
Seems like newer versions of 7.0 AGP fixes incompatibility. 
Closing this review as unnecessary.

**Pull request closed without merging**
